### ISSUE TITLE
Developper console content is blank in the screenshot of the report

### ISSUE THREAD

**Issue by StephaneColson** [morvader/ExploratoryTestingChromeExtension#2]
When using screenshot, if for example I have the developper tools opened then the content is not retrieved in the screenshot and remains empty.

In the Browser
![browserwhenscreenshot](https://cloud.githubusercontent.com/assets/1481595/17891893/bf747fb2-693e-11e6-9d39-4eb3faee5ef8.png)

In the report
![inthereport](https://cloud.githubusercontent.com/assets/1481595/17891903/c60b5ad0-693e-11e6-8d5b-27e5d1b93182.png)

Reproduced with Chrome Version 52.0.2743.82 (64-bit) on Debian when Console or Network opened (for example)

.

**Comment by morvader** [comment]
Hi @StephaneColson ,

Thanks for the report.

Actually I never thought about capturing the developer tools, it something i've never tested ;-)

Maybe it's a good idea to include this feature. I will have a look at it.

Thanks!

**Comment by StephaneColson** [comment]
Damn it was 7 years ago...not needed anymore
