### ISSUE TITLE
Impossible to export HTML Report

### ISSUE THREAD

**Issue by cedric190985** [morvader/ExploratoryTestingChromeExtension#3]
When I generate a report and I click on "Export Session to HTML" button I have an error and dl tab. 

On attachments you'are a list of issue that I had "Open" before the error (fake issue)

![image](https://cloud.githubusercontent.com/assets/17062644/18274991/65b6934a-7445-11e6-9d7c-1f40458bff82.png)

**Comment by morvader** [comment]
The problem seems to be related to some "special characters" like some accents or some combination of them.

I'll have a look. 

Thanks for reporting.

**Comment by cedric190985** [comment]
I try with many issue without "accents" and it is OK

**Comment by morvader** [comment]
There was a problem with the download approach I was ussing. It dind't work for large reports.

I thinks it's solved.

**Comment by cedric190985** [comment]
Tks
I modify a review of your tool
