### ISSUE TITLE
Extension Contains Malware

### ISSUE THREAD

**Issue by ckenst** [morvader/ExploratoryTestingChromeExtension#6]
Chrome just disabled the Exploratory Testing Chrome Extension I had installed with the note “This extension contains malware.”

Also looks like this extension is no longer available in the Chrome Store. Assuming these are related, is there any plan to fix?

**Comment by lanej0** [comment]
Anyone following along at home: @morvader has reached out to Google for further information.  In the last release, I rolled in [Bootstrap](https://getbootstrap.com/) for styling. 

Maybe it has something to do with [this](https://github.com/twbs/bootstrap/issues/23148)?  It's most likely a false positive, but pretty strange as Bootstrap is so widely used.

**Comment by morvader** [comment]
I'm very sorry, I don't know what is happening. I've contacted  Google to get some information.

**Comment by morvader** [comment]
The issue seems to be related to JQuery 3. Apparently at some point makes to a call to a remote resource, and this is considered as possible malware by Google.

I downgrade jQuery library to the previous version (1.11) and everything seems to be fine now.

Sorry for the inconvenience.
