### ISSUE TITLE
All Screenshot Links Open the Same Image

### ISSUE THREAD

**Issue by Snogren** [morvader/ExploratoryTestingChromeExtension#8]
**Summary:**

In the session report, all screenshot thumbnail links only open the most recent screenshot taken using the extension.

**To reproduce**:

1. Save a bug, a note, and another bug, each with a different screenshots.
2. Open the Session Report.
3. Hover over the screenshots. They should all show the correct image.
4. Click the first screenshot you took.
5. The most recent image is opened, from the latest bug.

Using Windows 10, Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Workaround**:

You can use the browser's zoom expand the thumbnail to a full image size and take a new screenshot of the thumbnail using a different application.

**Comment by morvader** [comment]
Hi @Snogren, 
You are absolutely right. Thanks a lot for the report. I'll try to fix it asap.

**Comment by morvader** [comment]
I've just published the fix.
It was a problem using a "var" declaration instead of "let" :s

Thank you so much for your time
